stages:
  - develop_generate
  - tag_generate
  - release

variables:
  GIT_STRATEGY: fetch

develop_generate:
  stage: develop_generate
  tags:
        - linux_docker_builder
  only:
    - master
  script:
    - chmod +x ./GeneratePDF.sh
    - docker login gitlab.tekniker.es:5001 --username $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - ./GeneratePDF.sh $CI_COMMIT_SHORT_SHA $CI_COMMIT_TIMESTAMP
  artifacts:
    paths:
      - LTS_103_Validation.pdf

tag_generate:
  stage: tag_generate
  tags:
        - linux_docker_builder
  only:
    - tags
  script:
    - chmod +x ./GeneratePDF.sh
    - docker login gitlab.tekniker.es:5001 --username $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - ./GeneratePDF.sh $CI_COMMIT_TAG $CI_COMMIT_TIMESTAMP
  artifacts:
    expire_in: never
    paths:
      - LTS_103_Validation.pdf

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:edge
  only:
    - tags
  script:
    - >
      release-cli create --name $CI_COMMIT_TAG
      --assets-link '{"name":"LTS_103_Validation.pdf","url":"'$CI_PROJECT_URL'/-/jobs/artifacts/'$CI_COMMIT_SHA'/raw/LTS_103_Validation.pdf?job=tag_generate"}'


      https://gitlab.tekniker.es/publico/3151-lsst/documentation/verifications/lts-103-mcs/-/jobs/artifacts/c2aa4b4843f25981173767a0775671d5ac7cc257/raw/LTS_103_Validation.pdf?job=tag_generate
