stages:
  - develop_generate
  - tag_generate
  - release

variables:
  GIT_STRATEGY: fetch

develop_generate:
  stage: develop_generate
  tags:
        - linux_docker_builder
  only:
    - master
  script:
    - chmod +x ./GeneratePDF.sh
    - docker login gitlab.tekniker.es:5001 --username $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - ./GeneratePDF.sh $CI_COMMIT_SHORT_SHA $CI_COMMIT_TIMESTAMP
  artifacts:
    paths:
      - LTS_103_Validation.pdf

tag_generate:
  stage: tag_generate
  image: bsantamaria/pandoc-extended
  only:
    - tags
  script:
    - ./generate_pdf $CI_COMMIT_TAG
  artifacts:
    expire_in: never
    paths:
      - LSST_HMI_SoftwareDocumentation.pdf

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:edge
  only:
    - tags
  script:
    - >
      release-cli create --name $CI_COMMIT_TAG
      --assets-link '{"name":"LSST_HMI_SoftwareDocumentation.pdf","url":"https://gitlab.tekniker.es/aut/projects/3151-LSST/LabVIEWCode/hmicomputers_documentation/-/jobs/artifacts/'$CI_COMMIT_SHA'/raw/LSST_HMI_SoftwareDocumentation.pdf?job=tag_generate"}'


